CN-258 adding primary keys
tradecentric/Magento_PurchaseOrder pull request #4
Opened 2024-09-26 13:42 UTC by tc-dan-bosler

Added Primary Keys to the sales_order_item_purchase_order & quote_item_purchase_order tables via the etc/db_schema.xml file.

2024-09-26 13:43 UTC, tc-dan-bosler commented
@tc-greg-lee once I can get Jay to approve the review, could you approve this merge to the main branch?  Thanks

2024-09-27 14:39 UTC, tc-greg-lee approved these changes
Thanks!

2024-10-01 15:43 UTC, p2g-jay-grayson commented on etc/db_schema.xml
> +		<constraint xsi:type="primary" referenceId="PRIMARY">
Is this just GH not formatting it correctly?  Or is not aligned with the other nodes?

2024-10-01 15:43 UTC, p2g-jay-grayson commented on etc/db_schema.xml
> +		<constraint xsi:type="primary" referenceId="PRIMARY">
Is this just GH not formatting it correctly?  Or is not aligned with the other nodes?

2024-10-01 15:44 UTC, p2g-jay-grayson requested changes
See inline

2024-10-01 16:14 UTC, tc-dan-bosler reviewed
Thanks! it should be aligned now!

2024-10-01 16:19 UTC, p2g-jay-grayson approved these changes

2024-10-01 16:20 UTC, merged